export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALES_EXECUTIVE = 'SALES_EXECUTIVE',
  CHANNEL_PARTNER = 'CHANNEL_PARTNER',
  TELECALLER = 'TELECALLER',
  CUSTOMER = 'CUSTOMER',
  VIEWER = 'VIEWER',
}
